### PR TITLE
fix: deprecation warning issue on chypotography keytypes

### PR DESCRIPTION
**Pull request by tsw025**
related to the ticket created here: https://github.com/Intility/fastapi-azure-auth/issues/119#issuecomment-1487220246

### CODE REVIEW

**Comment by tsw025** [comment]
Sorry, this is from the latest release of cryptography. 
  • Updating cryptography (39.0.1 -> 40.0.1)

I will close this as it is not yet updated

**Comment by JonasKs** [comment]
We also need to bump the required version in pyproject.toml 😊

**Comment by tsw025** [comment]
Thanks for the fast reply. seems like there's an network issue with the codecovrage pipeline

**Comment by JonasKs** [comment]
Pipelines resolved. Thank you for the PR 😊 I'll merge and release next week.

**Pull request merged**
