### PR TITLE
OpenApi schema test

### PR DESCRIPTION
**Pull request by enadeau**
- fix version comparison in skip condition for open api schema validation
- upgrade fastapi to 0.100.1

### CODE REVIEW

**Comment by enadeau** [comment]
I've tried backing off with the fastapi version upgrade because I thought that was causing the mypy issue and didn't want to get it mixed up with this simple fix. It seems however that something else is causing it. Doesn't seems related to this PR

**Comment by JonasKs** [comment]
I believe the MyPy issues has been resolved in another PR. 

Thank you so much for this - I'll check all PRs out on Monday, and hopefully have a release ready early next week 😊

**Comment by enadeau** [comment]
I figured out the cause was the version of pydantic used in the pre-commit hook. It automatically grabs the latest version which is now v2 but the library is not yet compatible. I'm pinning it for now and the compatibility issue can be resolved in an other PR.

**Comment by enadeau** [comment]
The pydantic compatibility issue are addressed in #144. We should probably merge it first so that we don't need to do any pinning here. I think it should also fix the failure that we see here with 3.12.

All problem in #142 are addressed. I needed to modify the name of the scheme. I've made something up, but it'll be good to hear what you think.

**Comment by JonasKs** [comment]
Could you rebase main? I'll make sure to get a release ASAP. Thank you so much for these!

**Review by JonasKs — APPROVED** [review]

**Comment by enadeau** [comment]
I've rebased but the spec with pydantic v2 is slightly different from the one with v1 causing all the v2 run to fail. 

I'm not quite sure what's the best solution here. We could either make another test specific to v2 schema or remove the test considering that validating the spec is good enough for us. Any thought on that?

**Comment by JonasKs** [comment]
I think we can just default to v2 here? And skip if version is 1.?

**Comment by enadeau** [comment]
I just did that. Good to go now

**Comment by JonasKs** [comment]
Thank you so much again, @enadeau 😊

**Pull request merged**
