### PR TITLE
fix: make tid and oid optional to allow User validation in B2C

### PR DESCRIPTION
**Pull request by davidhuser**
This fix is related to the discussion around B2C in Pull Request #140 (and issue #136).

It makes the claims `tid` and `oid` optional in the Pydantic `User` Model so that B2C auth won't fail when these claims in the token are missing.

### CODE REVIEW

**Comment by JonasKs** [comment]
Thank you! 

There’s something failing with mypy, I’ll have to investigate, unless you figure it out in the mean time 😊

**Comment by davidhuser** [comment]
Some proposed changes in the recent commit. One is adding type hints with Union plus casting to string, the other simply ignoring the mypy error, could not really figure it out why that occurs now.

**Comment by vjmadhal-silverstream** [comment]
Just out of curiosity as I found my way here from a linked issue. If tid becomes optional and B2CMultiTenantAuthorizationCodeBearer sets multi_tenant to true, then we'll want to verify our issuer and provide the iss_callable? That being the case, would Line 170 of auth.py still cause issues?

I'm actually in the process of configuring this for B2C and have found that I can't get it to work when it's looking for tid as it's not a claim that exists in the token, although iss does. If tid is hardcoded then is it optional? Sorry for asking here, I can comment in the issue if you'd prefer, it just seemed closer to where you were making a related change

**Comment by JonasKs** [comment]
I'm out of office until Monday, I'll make sure to go through all of this then. Sorry for the delays.

**Comment by JonasKs** [comment]
Hi! I'm back! Could you rebase main? Want to make sure tests pass with new changes before I merge 😄

**Comment by davidhuser** [comment]
did that, still some failures (in `test_openapi_scheme.py`)

**Comment by davidhuser** [comment]
ah, looks like it could be related to the works in #143

**Comment by enadeau** [comment]
Yes I think they should be resolved if we merge #143 first

**Comment by JonasKs** [comment]
I've merged that now. 😊 Please rebase

**Comment by davidhuser** [comment]
Not sure why the tests are still failing as I rebased, and my [branch](https://github.com/davidhuser/fastapi-azure-auth/tree/fix/b2c-optional-claims-tid-oid) says

> This branch is not behind the upstream `Intility/fastapi-azure-auth:main`. 
> No new commits to fetch.

**Comment by JonasKs** [comment]
Sure, that works for me too 😊 Thanks @davidhuser

**Pull request closed without merging**
