### PR TITLE
Updated docs for py3.8

### PR DESCRIPTION
**Pull request by manupatel007**
Updated part of documentation to include synced tabs for demonstrating different python-version code as followed(Thanks to Jonas for direct link to docusaurus doc's tab section)
image

Also, updated the readme to reflect support for Python 3.8.

### CODE REVIEW

**Comment by JonasKs** [comment]
That looks awesome! :clap: 

Could you change this too?   
bilde

Found [here](https://intility.github.io/fastapi-azure-auth/installation).

**Comment by manupatel007** [comment]
Sure, please let me know if there is anything else I am missing.

**Comment by JonasKs** [comment]
Looks perfect, thank you so much. 😊

**Review by JonasKs — APPROVED** [review]

**Comment by JonasKs** [comment]
Deployed now 😊

**Pull request merged**
