### PR TITLE
Feature/b2c support

### LINKED ISSUE #46: [Feature request] support for B2C tokens
**Describe the feature you'd like**

I noticed it's not possible to validate B2C tokens with this library, because it depends on the `x5c` field being present in the public key, and my organization's B2C public keys don't have this field. There is a simpler way to create the `cert_obj` that doesn't depend on this field https://python-jose.readthedocs.io/en/latest/jwk/index.html, which would allow for B2C tokens to be validated as well. I had to make some additional modifications to allow a user to override the openid_config url, but that may be specific to my organization. I'd be happy to contribute a pull request, if that is welcome? 

**Additional context**

### PR DESCRIPTION
**Pull request by robteeuwen**
Added support for tokens without `x5c` fields, and added optional `openid_config_url` override, this would close #46 

Not all tests are working yet, not sure if that is due to the code itself or due to the test config

### CODE REVIEW

**Comment by JonasKs** [comment]
Thank you so much! I’ll look into tests as soon as I can, but it might take a few days. 😊

**Comment by JonasKs** [comment]
You could look into creating the signing key from jwk instead of manually like I’ve done? Seems like it loads a bit more than just the public key.

**Comment by JonasKs** [comment]
Hi @robteeuwen !

I did some research over lunch and think I figured it out. In short, `n` == `modulus` and `e` == `exponent`, and with these two one can generate the public key. These are not generated properly through your code.

These matters so much now, because `x5c` is completely ignored by `python-jose`, as I've described in detail over in [this](https://github.com/mpdavis/python-jose/issues/289) issue.

Since Azure keys always consist of _both_ `n+e` and `x5c`, we can get away with removing the entire `x5c` from our mocked `keys` endpoint. However, we need to generate the `n` and `e` properly. Luckily, this is pretty easy, and most of the code needed is already provided in `utils.py` [here](https://github.com/Intility/fastapi-azure-auth/blob/main/tests/utils.py#L162-L166).

Wrap that in `construct` and success: 

```python
jwk.construct(
    signing_key_b.private_bytes(
        crypto_serialization.Encoding.PEM,
        crypto_serialization.PrivateFormat.PKCS8,
        crypto_serialization.NoEncryption(),
    ),
    'RS256',
).to_dict()

``` 

Let me know if anything is unclear. :smile:

**Comment by JonasKs** [comment]
I wanted to learn how to actually convert `n` and `e` properly, and this is the solution:

```python
base64.b64encode(signing_key_b.public_key().public_numbers().e.to_bytes(((signing_key_b.public_key().public_numbers().e.bit_length() + 7) // 8), 'big'))
base64.b64encode(signing_key_b.public_key().public_numbers().n.to_bytes(((signing_key_b.public_key().public_numbers().n.bit_length() + 7) // 8), 'big'))
```
Where `n.to_bytes(((signing_key_b.public_key().public_numbers().n.bit_length() + 7) // 8), 'big')` is stolen from [here](https://docs.python.org/3/library/stdtypes.html#int.to_bytes).

The [RFC](https://www.rfc-editor.org/rfc/rfc7518#section-6.3.1.1) says 
>    The "n" (modulus) parameter contains the modulus value for the RSA
   public key.  It is represented as a Base64urlUInt-encoded value.

which under Terminology can be read about:

>    **Base64urlUInt**
      The representation of a positive or zero integer value as the
      base64url encoding of the value's unsigned big-endian
      representation as an octet sequence.  The octet sequence MUST
      utilize the minimum number of octets needed to represent the
      value.  Zero is represented as BASE64URL(single zero-valued
      octet), which is "AA".


and now my head is boiling. Looking at the python-jose code, I can't find this solution, so I am sure it is a better way. :smile:

**Comment by robteeuwen** [comment]
hey Jonas, thanks so much for looking into this. I'm not sure I'm following completely. I tried to make some changes like the ones you suggest, but my tests are still failing. So first things first, do you think I'm generating the cert_obj incorrectly in the application code ([here](https://github.com/robteeuwen/fastapi-azure-auth/blob/c67ff1fd614602b84156ba9388e18fa9fbe02ccc/fastapi_azure_auth/openid_config.py#L102)) or do you think they keys are only generated incorrectly in the tests?

**Comment by JonasKs** [comment]
Why is it required to pass in `config_url`? How does this endpoint look for B2C? Could we simplify it? At the moment we have `SingleTenant` and `MultiTenant`, could we add one `B2C` class which configures this nicely instead?

**Comment by robteeuwen** [comment]
> 

That's a good question. In my organization's case the domain is different for B2C (it's a custom domain). This may be non standard, but in general, I think it's nice to have the option to override the config_url, since you can also override the other urls. But I set it to optional, so it's not required to pass it. 

In case this is non-standard B2C behavior, I guess it doesn't technically belong to the same feature as adding B2C support, so maybe it belongs in a different PR. 

Another thing that's different is that B2C openid config url includes a policy: https://docs.microsoft.com/en-us/azure/active-directory-b2c/openid-connect

**Comment by JonasKs** [comment]
Hi @robteeuwen, do you have any questions or want me to help out with something? 😊

**Comment by JonasKs** [comment]
Hi @robteeuwen , I’ll finish up this PR with the current changes this week if I don’t hear back. The specific B2C class and docs can be another PR, this PR is a nice start to all of that.

**Comment by JonasKs** [comment]
No worries! I’ll see what I can do 😊 

Yeah, a test or two is missing. Would also love to include documentation(like I have for single- and multi-tenant applications) for B2C, but don’t really need that to merge this.

**Comment by JonasKs** [comment]
I've removed the setting from `SingleTenantAzureAuthorizationCodeBearer` and `MultiTenantAzureAuthorizationCodeBearer`, so that you have to use the `AzureAuthorizationCodeBearerBase` directly. I have not found any case where this is required for normal tenants, only for B2C, so don't see a reason to expose the setting. 

I've added a test and cleaned up a little. Will merge and release ASAP.

**Comment by JonasKs** [comment]
I've merged and creates a release - thank you so much!

I would love documentation(like we got for single- and multi-tenant apps) and a specific `B2C`-class in the future, if you're interested in helping out with that😊

**Comment by lsmith77** [comment]
@robteeuwen thank you for this! do you have some documentation or at least some example code/config you can share to get this setup?

**Comment by lsmith77** [comment]
for now I am seeing if using https://github.com/425show/fastapi_microsoft_identity#2-azure-ad-b2c-authentication gets me started in the right direction

**Pull request merged**
