### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by kristiqntashev**
This PR is regarding only improving the UnitTests(adding some parametrized tests). Keep in mind behavior and the number of the tests are the same.  Just removing not needed noise in the code.

Directly reject it if doesn't look reasonable to you.

### CODE REVIEW

**Comment by JonasKs** [comment]
I will go through it all tomorrow😊 Thank you for the PR!!

**Comment by JonasKs** [comment]
I absolutely love this! If you do this out of the main branch (renaming the `generate_obj` function etc.) it would be _awesome_

**Comment by kristiqntashev** [comment]
@JonasKs  I will rebase this.

**Comment by kristiqntashev** [comment]
@JonasKs Should you rebase it or do I have to create a brand new MR?

**Comment by JonasKs** [comment]
@kristiqntashev , you have to sync your `main` branch. See the GitHub documentation [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

You can then either rebase main into your `improve_tests` branch, or as you said, create a new branch from main. I'd rebase, but it can be a hassle if it is the first time. So do whatever you find easiest 😊

**Comment by JonasKs** [comment]
Awesome 😊 

I think, in general, the test suite for this package is a bit too repetitive. Right now the `b2c` folder and `multi-tenant` folder is more or less the same (except for which class is used). I think we could definitely make this into just one folder, and remove a good chunk of tests.. If we're to add a `B2CSingleTenantAuthorizationBearer`, this don't really scale. One code change would break 4 sets of equal tests.

**Comment by kristiqntashev** [comment]
I will do it next week quite busy this.

**Comment by JonasKs** [comment]
No rush, thank you so much for contributing 😊

**Comment by JonasKs** [comment]
Closing for inactivity. Feel free to re-open.

**Pull request closed without merging**
