### PR TITLE
Improve documentation. Close #70

### LINKED ISSUE #70: [BUG/Question] Minor error in documentation
Thank you for this excellent module - and the fantastic documentation. I found a small typo in the section [Calling your APIs from Python
](https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python). It should be 
`'client_id': settings.APP_CLIENT_ID,` and not `'client_id': settings.OPENAPI_CLIENT_ID,`. 

I hope you will continue to maintain this project - it has been a time-saver for me.

### PR DESCRIPTION
**Pull request by JonasKs**
Closes #70

image  
and  
image

### CODE REVIEW

**Comment by Christian-Schultz** [comment]
I think the wording is much more clear now - I now see that is what you meant by the sentence _(ideally you'd create a new one for your new application, but we'll reuse this for now)_ but I missed it. I'm sure I wouldn't miss it now.

**Comment by JonasKs** [comment]
Awesome! I'll merge now. Thank you so much for the feedback! ❤️

**Comment by Christian-Schultz** [comment]
I have another suggestion to the documentation if you'd like more feedback?

**Comment by JonasKs** [comment]
Please come with it all, @Christian-Schultz ! And PRs too, if you'd like 😊

**Comment by Christian-Schultz** [comment]
Awesome - I will make a new issue. I would make a PR - but for this particular issue I don't think I have the expertise to write it up properly :)

**Pull request merged**
