### PR TITLE
parse auth_time as an int

### PR DESCRIPTION
**Pull request by roman-van-der-krogt**
Fix for https://github.com/Intility/fastapi-azure-auth/issues/166

### CODE REVIEW

**Comment by JonasKs** [comment]
Thanks so much 😊 I'll get a new release out tomorrow.

**Comment by roman-van-der-krogt** [comment]
@JonasKs Gentle reminder to create a new release with this fix, pretty please?

**Comment by JonasKs** [comment]
I'll get a release out tomorrow!

**Comment by JonasKs** [comment]
I've created a new release. Thanks for the contribution 😊

**Pull request merged**
