### PR TITLE
Trying a condition for pydantic v2 support.

### PR DESCRIPTION
**Pull request by bmoore**
in regards to https://github.com/Intility/fastapi-azure-auth/issues/150 I am getting warnings about the field_validator. I'm not sure if we want to have some future proofing around the validator warning. This change cleans up the warning I get from testing when using Pydantic v2

### CODE REVIEW

**Comment by JonasKs** [comment]
I think we can start dropping v1 support, so no need to keep v1 validators. 

I will have more time mid November, and hope to have a pydantic v2-only release out in December.

**Comment by JonasKs** [comment]
Sorry for the long delay on this one. 

I would like to:
- Remove all token v1 support
- Only support Pydantic v2 for new releases

This should increase the maintainability of this packge. 

I thought I'd ask you whether you would like to help/review, or if I should go ahead myself. 😊

**Comment by jrabensc** [comment]
What's the current status? I would like to remove these deprecation warnings from my tests. Do you need any help?

**Comment by JonasKs** [comment]
Any PR with the removal of v1 support would be appreciated. 😊

**Comment by JonasKs** [comment]
Thanks so much, sorry it took a while to get rid of these. v5 will fix this, see #200

**Pull request closed without merging**
